[project]
name = "pcst_fast"
version = "1.0.10+numpy2"
description = "A fast implementation of the Goemans-Williamson scheme for the prize-collecting Steiner tree / forest problem."
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "ludwigschmidt"},
    {name = "alexlenail"},
]
requires-python = ">=3.11"

[project.urls]
homepage = "https://github.com/fraenkel-lab/pcst_fast"

[tool.setuptools_scm]

[tool.cibuildwheel]
build = "cp311-manylinux_x86_64 cp312-manylinux_x86_64 cp313-manylinux_x86_64"
test-requires = "pytest numpy~=2.2"
test-skip = "*-musllinux_* *-manylinux_i686 pp39-manylinux_x86_64 pp*-win_amd64 pp*-macosx_x86_64 cp313-win*"
test-command = "pytest {project}/src"
build-verbosity = 1

[tool.cibuildwheel.macos]
before-test = "pip cache remove numpy; brew install openblas; OPENBLAS=\"$(brew --prefix openblas)\" pip install --no-cache-dir -U pip numpy"
